version: '2'
services:
  app:
    image: budget_service
    command: bash -c "RAILS_ENV=development bundle exec rake db:create db:schema:load && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: budget_app
    tty: true
    stdin_open: true
    environment:
      - DOCKER_DB_HOST=my_postgres
    volumes:
      - ../budget_planner:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      default:
        aliases:
          - dev.budget.com
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
